kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pxbackup-local
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP  # For our application
  - containerPort: 30500
    hostPort: 30500
    protocol: TCP  # For Flask application
  - containerPort: 30432
    hostPort: 30432
    protocol: TCP  # For PostgreSQL
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP  # For Keycloak
  - containerPort: 30200
    hostPort: 30200
    protocol: TCP  # For Vault
  - containerPort: 30379
    hostPort: 30379
    protocol: TCP  # For Redis
  - containerPort: 30300
    hostPort: 30300
    protocol: TCP  # For Gitea
  - containerPort: 30800
    hostPort: 30800
    protocol: TCP  # For Mock Inventory
  - containerPort: 30900
    hostPort: 30900
    protocol: TCP  # For Prometheus
