kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pxbackup-local
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP  # For our application
  - containerPort: 30432
    hostPort: 30432
    protocol: TCP  # For PostgreSQL
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP  # For Keycloak
  - containerPort: 30200
    hostPort: 30200
    protocol: TCP  # For Vault
